#!/usr/bin/env node
/**
 * build.js — produces dist/index.html, a fully self-contained offline HTML.
 *
 * What gets embedded:
 *   • face-api.js (1.2 MB, inlined as <script>)
 *   • tinyFaceDetector, faceExpressionNet, faceLandmark68Net models
 *     (weights manifest JSON + .bin as base64 — ~940 KB combined base64)
 *
 * What still requires a network:
 *   • MediaPipe Hands WASM (palm-stop feature only — fails gracefully)
 *   • XToys cloud webhook (optional — local webhook also available)
 *
 * Usage:  node build.js
 * Output: dist/index.html   (~2.5 MB, fully offline)
 */

const fs   = require('fs');
const path = require('path');

const ROOT  = __dirname;
const NM    = path.join(ROOT, 'node_modules');
const SRC   = path.join(ROOT, 'index.html');
const DIST  = path.join(ROOT, 'dist');
const OUT   = path.join(DIST, 'index.html');

// ── Assets to embed ──────────────────────────────────────────
const FACE_API_JS = path.join(NM, '@vladmandic/face-api/dist/face-api.js');
const MODEL_DIR   = path.join(NM, '@vladmandic/face-api/model');

const MODELS = [
    'tiny_face_detector_model',
    'face_expression_model',
    'face_landmark_68_model',
];

// ── Build embedded model map ─────────────────────────────────
function buildModelMap() {
    const map = {};
    for (const name of MODELS) {
        const manifestPath = path.join(MODEL_DIR, name + '-weights_manifest.json');
        const binPath      = path.join(MODEL_DIR, name + '.bin');

        map[name + '-weights_manifest.json'] = fs.readFileSync(manifestPath, 'utf8');
        map[name + '.bin']                   = fs.readFileSync(binPath).toString('base64');
    }
    return map;
}

// ── Fetch-interceptor snippet injected before face-api ───────
function buildFetchInterceptor(map) {
    const entries = Object.entries(map).map(([k, v]) => {
        const escaped = v.replace(/\\/g, '\\\\').replace(/`/g, '\\`');
        return '  ' + JSON.stringify(k) + ': `' + escaped + '`';
    }).join(',\n');

    return `<script id="offline-model-data">
// Embedded model data — generated by build.js
(function(){
const OFFLINE = {
${entries}
};
const _fetch = window.fetch.bind(window);
window.fetch = function(url, opts) {
    try {
        const u = url instanceof Request ? url.url : String(url);
        const key = u.split('/').pop().split('?')[0];
        if (key in OFFLINE) {
            const raw = OFFLINE[key];
            if (key.endsWith('.bin')) {
                const bin  = atob(raw);
                const buf  = new Uint8Array(bin.length);
                for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
                return Promise.resolve(new Response(buf.buffer, { status: 200,
                    headers: { 'Content-Type': 'application/octet-stream' } }));
            }
            return Promise.resolve(new Response(raw, { status: 200,
                headers: { 'Content-Type': 'application/json' } }));
        }
    } catch(_) {}
    return _fetch(url, opts);
};
})();
</script>`;
}

// ── Main ─────────────────────────────────────────────────────
console.log('Building offline single-file HTML...\n');

let html = fs.readFileSync(SRC, 'utf8');

// 1. Inline face-api.js immediately before </head>
console.log('  Inlining face-api.js (' + Math.round(fs.statSync(FACE_API_JS).size / 1024) + ' KB)...');
const faceApiSrc = fs.readFileSync(FACE_API_JS, 'utf8');
const faceApiTag = '<script id="face-api-inline">\n' + faceApiSrc + '\n</script>';

// 2. Build and prepend fetch interceptor
console.log('  Encoding model weights...');
const modelMap    = buildModelMap();
const totalBinKB  = MODELS.reduce((s, n) => s + fs.statSync(path.join(MODEL_DIR, n + '.bin')).size, 0);
console.log('  Models: ' + MODELS.join(', ') + ' (' + Math.round(totalBinKB / 1024) + ' KB raw)');

const interceptor = buildFetchInterceptor(modelMap);

// Inject interceptor + face-api before </head>
html = html.replace('</head>', interceptor + '\n' + faceApiTag + '\n</head>');

// 3. Patch loadFaceApiLibrary() to skip dynamic script loading and use
//    the inline library + embedded model URI '/offline/'
//    (fetch interceptor matches filenames regardless of path prefix)
html = html.replace(
    `async function loadFaceApiLibrary() {
    const cdnKey = el.cdnSelect.value;
    const cdn = CDN[cdnKey];
    showStatus('Loading Face-API library\u2026', 'info');
    addLog('Loading face-api from ' + cdnKey + '\u2026');
    el.startBtn.disabled = true;
    state.isLibLoaded = false;
    try {
        document.querySelectorAll('script[data-dyn]').forEach(s => s.remove());
        if (window.faceapi) window.faceapi = undefined;
        await loadScript(cdn.lib);
        if (typeof faceapi === 'undefined') throw new Error('faceapi object not found after script load');`,
    `async function loadFaceApiLibrary() {
    showStatus('Initialising embedded library\u2026', 'info');
    addLog('Using bundled face-api (offline build)\u2026');
    el.startBtn.disabled = true;
    state.isLibLoaded = false;
    try {
        if (typeof faceapi === 'undefined') throw new Error('face-api.js not bundled correctly');`
);

// Replace model CDN path with '/offline/' — the fetch interceptor matches by filename only
html = html.replace(
    `await Promise.all([
            faceapi.nets.tinyFaceDetector.loadFromUri(cdn.models),
            faceapi.nets.faceExpressionNet.loadFromUri(cdn.models),
            faceapi.nets.faceLandmark68Net.loadFromUri(cdn.models)
        ]);`,
    `await Promise.all([
            faceapi.nets.tinyFaceDetector.loadFromUri('/offline/'),
            faceapi.nets.faceExpressionNet.loadFromUri('/offline/'),
            faceapi.nets.faceLandmark68Net.loadFromUri('/offline/')
        ]);`
);

// 4. Add "Local Server" option to CDN selector and webhook type selector
// (these are already in the source; the offline build just makes everything work)

// 5. Write output
fs.mkdirSync(DIST, { recursive: true });
fs.writeFileSync(OUT, html, 'utf8');

const outKB = Math.round(fs.statSync(OUT).size / 1024);
console.log('\n✓ dist/index.html  (' + outKB + ' KB)');
console.log('\nOpen dist/index.html in any browser — no server or internet needed.');
console.log('(Palm detection still needs internet for MediaPipe WASM — fails silently.)');
